baseURL = "https://covid.jonblatho.com/"
languageCode = "en-us"
title = "COVID-19 in Howell County, MO"
publishDir = "docs"
disableKinds = ["sitemap", "RSS", "taxonomy", "section", "term"]
[minify]
  minifyOutput = true
[module]
  [[module.mounts]]
  source = "assets"
  target = "assets"
  [[module.mounts]]
  source = "node_modules/chart.js/dist/chart.min.js"
  target = "assets/js/chart.min.js"
  [[module.mounts]]
  source = "node_modules/chartjs-plugin-annotation/dist/chartjs-plugin-annotation.min.js"
  target = "assets/js/chartjs-plugin-annotation.min.js"

[deployment]
  [[deployment.targets]]
  name = "covid-19"
  URL = "s3://covid.jonblatho.com?region=us-west-2"
  cloudFrontDistributionID = "E2MHGA725T05JX"
  [[deployment.matchers]]
  pattern = "^sitemap\\.xml$"
  contentType = "application/xml"
  gzip = true
  [[deployment.matchers]]
  pattern = "^.+\\.(html|xml|json)$"
  gzip = true