name: Archive HCHD Dashboard

on:
  workflow_dispatch:

jobs:
  archive:
    name: Archive HCHD Dashboard
    runs-on: ubuntu-latest
    
    steps:
      # Archive HCHD dashboard
      - name: Archive HCHD Dashboard
        uses: JamieMagee/wayback@v1.3.15
        id: archive
        with:
          url: https://allthingsmissouri.org/county-covid-19-dashboards/howell-county/
          saveErrors: false
          saveOutlinks: true
          saveScreenshot: false
    outputs:
      archive_url: ${{ steps.archive.outputs.wayback_url }}
  update:
    name: Update Data with URL
    needs: archive
    if: needs.archive.outputs.archive_url != ''
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Setup Python
        uses: "actions/setup-python@v2"
        with:
          python-version: '3.9.2'

      - name: Add URL to Data
        run: python add-source-url.py ${{ needs.archive.outputs.archive_url }}

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7
        with:
          add: 'assets/ content/ daily-data/ data/ docs/'
          default_author: github_actions
          message: 'chore: add archive URL'
          signoff: true
          branch: main
          push: true