name: Auto-Archive HCHD Dashboard

on:
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: jonblatho/wayback@release
      with:
        url: https://allthingsmissouri.org/county-covid-19-dashboards/howell-county/
        saveErrors: false
        saveOutlinks: true
        saveScreenshot: false