name: Auto-Update

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  update:
    name: Update Data
    runs-on: ubuntu-latest
    env:
      TZ: America/Chicago
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Auto-Update Data
        run: |
          python autoupdate.py
          git add daily-data/ --intent-to-add

      - name: Check for New Data
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: |
            daily-data

      - name: Commit and Push (Update)
        uses: EndBug/add-and-commit@v7
        with:
          add: 'content/ daily-data/'
          default_author: github_actions
          message: 'chore: add daily data'
          branch: main
          push: false

      # Archive the HCHD dashboard to the Wayback Machine
      - name: Archive HCHD Dashboard
        uses: JamieMagee/wayback@v1.3.19
        id: archive
        if: steps.changed_files.outputs.files_changed == 'true'
        continue-on-error: true
        with:
          url: https://allthingsmissouri.org/county-covid-19-dashboards/howell-county/
          saveErrors: false
          saveOutlinks: true
          saveScreenshot: false
      
      # Notify of archive step failure if needed
      - name: Create Issue for Archive Failure
        uses: imjohnbo/issue-bot@v3.3.3
        if: steps.archive.outcome == 'failure'
        with:
          assignees: jonblatho
          title: HCHD dashboard archive failed
          labels: bug
          body: |-
            Encountered an error when attempting to archive the HCHD dashboard to the Wayback Machine.
          pinned: true
          token: ${{ secrets.GH_PAT }}

      # If the archive was successful, add the archive URL to the data
      - name: Add Archive URL to Data
        if: steps.archive.outcome == 'success' && steps.archive.outputs.wayback_url != ''
        id: add_archive_url
        run: python add-source-url.py ${{ steps.archive.outputs.wayback_url }}

      - name: Commit and Push (Archive)
        uses: EndBug/add-and-commit@v7
        if: steps.add_archive_url.outcome == 'success' && steps.archive.outputs.wayback_url != ''
        with:
          add: 'daily-data/'
          default_author: github_actions
          message: 'chore: add archive URL'
          branch: main
          push: true
          
      - name: Push Retry
        run: git push
