name: Auto-Update and Rebuild

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4,5,15 * * *" # Run at 11 PM, midnight, and 10 AM CDT

jobs:
  update:
    name: Update Data
    runs-on: ubuntu-20.04
    env:
      TZ: America/Chicago
    steps:
      ###### SETUP ######
      # Checkout repo from GitHub
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      # Bring in GPG key for signing commit
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Setup Git
        run: |
          git config user.name "Jonathan Thornton [Automated]"
          git config user.email "github+bot@jonblatho.com"

      # Set up Python
      - name: Setup Python
        uses: "actions/setup-python@v2"
        with:
          python-version: '3.9.2'

      ###### UPDATE DATA ######
      - name: Auto-Update Data
        run: |
          python autoupdate.py
          git add daily-data/ --intent-to-add
      # Check for changed files
      - name: Check for New Data
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: daily-data

      # Archive the HCHD dashboard if possible
      - name: Archive HCHD Dashboard
        uses: JamieMagee/wayback@v1.3.0
        id: archive
        if: steps.changed_files.outputs.files_changed == 'true'
        with:
          url: https://allthingsmissouri.org/county-covid-19-dashboards/howell-county/
          saveErrors: false
          saveOutlinks: true
          saveScreenshot: false

      # Insert the archive URL into the daily-data file
      - name: Add URL to Data
        if: steps.archive.outputs.wayback_url != '' && steps.changed_files.outputs.files_changed == 'true'
        run: python add-archive-url.py ${{ steps.archive.outputs.wayback_url }}

      # Install Hugo and NPM (and dependencies)
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        if: steps.changed_files.outputs.files_changed == 'true'
        with:
          hugo-version: 'latest'
          extended: true
      - name: Install NPM
        uses: actions/setup-node@v1
        if: steps.changed_files.outputs.files_changed == 'true'
      - name: Install Chart.js and Dependencies
        run: npm install
        if: steps.changed_files.outputs.files_changed == 'true'

      ###### PROCESS AND REBUILD ######
      - name: Process Data
        if: steps.changed_files.outputs.files_changed == 'true'
        run: python process.py

      - name: Rebuild Site
        if: steps.changed_files.outputs.files_changed == 'true'
        run: hugo

      ###### COMMIT AND PUSH ######
      - name: Commit Changes and Push
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          git add docs/
          git add daily-data/
          git commit -am 'chore: regenerate site [automated]'
          git push