name: Auto-Update and Rebuild

on:
  schedule:
    - cron: "*/15 4-6 * * *" # Run every 15 min between 10 PM and 12 AM CST
    # - cron: "*/15 3-5 * * *" # Run every 15 min between 11 PM and 12 AM CDT

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      TZ: America/Chicago
    steps:
      ###### SETUP ######
      # Checkout repo from GitHub
      - uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      # Set timezone to Central Time
      - run: date

      # Bring in GPG key for signing commit
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - run: git config user.name "Jonathan Thornton [Automated]"
      - run: git config user.email "github+bot@jonblatho.com"

      # Set up Python and Hugo
      # - uses: "actions/setup-python@v2"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      ###### UPDATE/BUILD ######
      - name: Auto-Update Data
        run: |
          python autoupdate.py
          python process.py
          hugo

      ###### COMMIT AND PUSH ######
      - name: Commit Changes
        run: git commit -am '[automated] regenerate site'

      - name: Push Changes
        run: git push
      