name: Auto-Update and Rebuild

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4,5,15 * * *"

jobs:
  update:
    name: Update Data
    runs-on: ubuntu-20.04
    env:
      TZ: America/Chicago
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Setup Git
        run: |
          git config user.name "Jonathan Thornton [Automated]"
          git config user.email "github+bot@jonblatho.com"
      - name: Setup Python
        uses: "actions/setup-python@v2"
        with:
          python-version: '3.9.2'
      - name: Auto-Update Data
        run: |
          python autoupdate.py
          python process.py
          git add daily-data/ --intent-to-add
      - name: Check for New Data
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: |
            daily-data
            data
      - name: Commit Changes and Push
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          git add docs/
          git add daily-data/
          git commit -am 'chore: add daily data [automated]'
          git push
    outputs:
      new_data: ${{ steps.changed_files.outputs.files_changed }}
  archive:
    name: Archive HCHD Dashboard
    runs-on: ubuntu-20.04
    needs: update
    if: needs.update.outputs.new_data == 'true'
    env:
      TZ: America/Chicago
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Setup Git
        run: |
          git config user.name "Jonathan Thornton [Automated]"
          git config user.email "github+bot@jonblatho.com"
      - name: Setup Python
        uses: "actions/setup-python@v2"
        with:
          python-version: '3.9.2'
      - name: Archive HCHD Dashboard
        uses: JamieMagee/wayback@v1.3.0
        id: archive
        with:
          url: https://allthingsmissouri.org/county-covid-19-dashboards/howell-county/
          saveErrors: false
          saveOutlinks: true
          saveScreenshot: false
      - name: Add URL to Data
        if: steps.archive.outputs.wayback_url != ''
        run: python add-archive-url.py ${{ steps.archive.outputs.wayback_url }}
      - name: Commit Changes and Push
        if: steps.archive.outputs.wayback_url != ''
        run: |
          git add docs/
          git add daily-data/
          git commit -am 'chore: add archive URL [automated]'
          git push
  rebuild:
    name: Rebuild Site
    runs-on: ubuntu-20.04
    needs: [update, archive]
    if: needs.update.outputs.new_data == 'true'
    env:
      TZ: America/Chicago
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Setup Git
        run: |
          git config user.name "Jonathan Thornton [Automated]"
          git config user.email "github+bot@jonblatho.com"
      - name: Setup Python
        uses: "actions/setup-python@v2"
        with:
          python-version: '3.9.2'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Install NPM
        uses: actions/setup-node@v1
      - name: Install Chart.js and Dependencies
        run: npm install
      - name: Rebuild Site
        run: npm run rebuild
      - name: Commit Changes and Push
        run: |
          git add docs/
          git add daily-data/
          git commit -am 'chore: rebuild site [automated]'
          git push