name: Auto-Update and Rebuild

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 3-5 * * *" # Run every 15 min between 10 PM and 12 AM CDT

jobs:
  update:
    name: Update Data
    runs-on: ubuntu-20.04
    env:
      TZ: America/Chicago
    steps:
      ###### SETUP ######
      # Checkout repo from GitHub
      - uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      # Bring in GPG key for signing commit
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - run: git config user.name "Jonathan Thornton [Automated]"
      - run: git config user.email "github+bot@jonblatho.com"

      # Set up Python
      - uses: "actions/setup-python@v2"

      ###### UPDATE DATA ######
      - name: Auto-Update Data
        run: |
          python autoupdate.py
          python process.py

      # Check for changed files
      - name: Check for New Data
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: |
             daily-data
             data
             assets/js

      # Install Hugo and NPM (and dependencies)
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        if: steps.changed_files.outputs.files_changed == 'true'
        with:
          hugo-version: 'latest'
          extended: true
      - name: Install NPM
        uses: actions/setup-node@v1
        if: steps.changed_files.outputs.files_changed == 'true'
      - name: Install Chart.js and Dependencies
        run: npm install
        if: steps.changed_files.outputs.files_changed == 'true'

      ###### REBUILD ######
      - name: Rebuild Site
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          hugo

      ###### COMMIT AND PUSH ######
      - name: Commit Changes
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          git add docs/
          git add daily-data/
          git commit -am 'chore: regenerate site [automated]'

      - name: Push Changes
        if: steps.changed_files.outputs.files_changed == 'true'
        run: git push
      