name: Unit Tests

on:
  pull_request:
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  test_scripts:
    name: Test Scripts
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          python-version: 3.9.6

      - name: Install Python Dependencies
        run: conda install --file requirements.txt

      - name: Run Tests
        run: python -m pytest utilities/test.py

      - name: Gather Coverage
        run: coverage run -m pytest utilities/test.py

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          files: .coverage