name: Unit Tests

on:
  pull_request:
  push:
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  test_scripts:
    name: Test Scripts
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'

      - name: Install Dependencies
        run: python -m pip install -r requirements.txt

      - name: Run Tests
        run: python -m pytest test.py

      - name: Gather Coverage
        run: |
          coverage run -m pytest test.py
          coverage xml

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true