name: Test Site Build

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_build:
    name: Test Site Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Install NPM
        uses: actions/setup-node@v1
      - name: Install Chart.js and Dependencies
        run: npm install
      - name: Rebuild Site
        run: hugo